apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "k8s-referencia.persistentVolumeClaimName" . }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName:  {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 10Gi
