apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8s-referencia.stressJobName" . }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      parallelism: 1
      initContainers:
      - name: iperf3
        image: {{ printf "%s:%s" .Values.image.iperf3.repository .Values.image.iperf3.version }}
        imagePullPolicy: Always
        args: [ {{ printf "-c %s -p 5000 -i 1 -t %s -J --logfile /mnt/log/iperf3_ref_tcp.json" (include "k8s-referencia.iPerfServerName" . | quote) .Values.timeout }} ]
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - mountPath: "/mnt/log"
          name: storage
      containers:
      - name: k8s-collector
        image: {{ printf "%s:%s" .Values.image.k8sCollector.repository .Values.image.k8sCollector.version }}
        imagePullPolicy: Always
        env:
        - name: CONNECTION_STRINGS__BLOB_STORAGE
          value: {{ .Values.blobConnectionString }}
        args: ["collect", "-s=/mnt/log",  {{ printf "-c=%s" .Values.blobContainerName }}]
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - mountPath: "/mnt/log"
          name: storage
      restartPolicy: OnFailure
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: {{ include "k8s-referencia.persistentVolumeClaimName" . }}
