# Default values for k8s-referencia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namePrefix: ""

image:
  iperf3:
    repository: mlabbe/iperf
    version: 'latest'
  sockperf:
    repository: maxandriani/sockperf
    version: '3.10'
  etgServer:
    repository: maxandriani/etg-server
    version: '1.0.0'
  k8sCollector:
    repository: maxandriani/k8s-collector
    version: '1.0.0'

podAnnotations:
  test-type: reference

storageClassName: managed-csi

host1Name: host1
host2Name: host2
