apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-referencia.iPerfServerName" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "k8s-referencia.iPerfServerName" . }}
  template:
    metadata:
      labels:
        app: {{ include "k8s-referencia.iPerfServerName" . }}
        
    spec:
      containers:
      - name: iperf-server
        image: {{ printf "%s:%s" .Values.image.iperf3.repository .Values.image.iperf3.version }}
        args: ["-s", "-p 5000"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
        ports:
        - containerPort: 5000
          name: iperf-server

    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.azure.com/agentpool
            operator: In
            values:
            - {{ .Values.host1Name }}
