apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-referencia.etgServer" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "k8s-referencia.etgServer" . }}
  template:
    metadata:
      labels:
        app: {{ include "k8s-referencia.etgServer" . }}
        
    spec:
      containers:
      - name: iperf-server
        image: {{ printf "%s:%s" .Values.image.etgServer.repository .Values.image.etgServer.version }}
        args: ["-p", "5000"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
        ports:
        - containerPort: 5000
          name: etg-server

    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.azure.com/agentpool
            operator: In
            values:
            - {{ .Values.host2Name }}
