apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-referencia.etgServer" . }}
  labels:
    {{- include "k8s-referencia.labels" . | nindent 4 }}
spec:
  clusterIP: None # Headless
  selector:
    app: {{ include "k8s-referencia.etgServer" . }}
  ports:
  - protocol: TCP
    port: 5000
    targetPort: etg-server
