apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "k8s-referencia.etgClient" . }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      parallelism: 1
      containers:
      - name: etg-client
        image: {{ printf "%s:%s" .Values.image.etgClient.repository .Values.image.etgClient.version }}
        args: ["-c", "/root/etgConfig"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
        ports:
        - containerPort: 5000
          name: etg-client
        volumeMounts:
        - name: config-volume
          mountPath: /root/etgConfig
          subPath: etgConfig
      restartPolicy: OnFailure
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "k8s-referencia.etgClient" . }}

    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.azure.com/agentpool
            operator: In
            values:
            - {{ .Values.host1Name }}
